@isTest
private class HelloWorldTestClass {
 
private static void test(){
    System.debug('Hello World');
} 
/* Test.startTest();
 // Insert book
 insert b;
 
 Test.stopTest();
 
 // Retrieve the new book
 b = [SELECT Price__c FROM Book__c WHERE Id =:b.Id];
 System.debug('Price after trigger fired: ' + b.Price__c);
 
 // Test that the trigger correctly updated the price
 System.assertEquals(90, b.Price__c);
 }*/
} 